name: Lint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Check workflow commits
      run: |
         cat .github/workflows/*.yml | bash <(curl -sSL "https://raw.githubusercontent.com/shazow/check-workflow-commits/main/check-workflow-commits")
